global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ACH Processing Backend
  - job_name: 'ach-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # PostgreSQL metrics (if using local PostgreSQL)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Application-specific metrics
  - job_name: 'ach-transactions'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/transactions'
    scrape_interval: 30s

  - job_name: 'ach-nacha-files'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics/nacha'
    scrape_interval: 60s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/health'
    scrape_interval: 30s